name: Release Library

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npx nx build schematics --prod --skip-nx-cache

      # Explicitly ensure npm registry is set to official npm registry
      - name: Configure npm registry
        run: |
          npm config set registry https://registry.npmjs.org/
          echo "Current registry: $(npm config get registry)"

      # Create .npmrc file with auth token for publishing
      - name: Create .npmrc file
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd dist/libs/YOUR_LIB_NAME
          echo "Creating package-specific .npmrc"
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "Publishing with explicit registry"
          npx semantic-release --debug
